### PR TITLE
Skeleton Cards - "Its bone" - American Psycho

### PR DESCRIPTION
**Pull request by ajbraus**
Hi there, I ❤️  Skeleton. 

I also like using cards in my designs, so I added some super minimalist cards, and a anchor-tag card. I don't want to bloat this refined library, but a card is so versatile. 

Can't help but remember the business card exchange scene in American Psycho. "Its bone". wowsa creepy.

### CODE REVIEW

**Comment by enlore** [comment]
I'll pull this down in the next couple nights and take a look.

**Comment by enlore** [comment]
Glad to see Skeleton getting love!

Personally, I like cards. I think they can be used to great effect to visually group related info. 

They also seem to have gained some popularity in mobile UI/UX design. I'm still working through a bit of research on their prevalence in the wild, though I can say that I've seen them in a few high profile places.

I think I can see them becoming a part of Skeleton core. Let me dig a little more on that.

In the mean time, can you make a few changes to your PR? 

Don't edit the files in the `dist` directory. They get regenerated and overwritten with every release.

Instead, go down into `src/core` and find a module that's related, or make a new one. Doing `src/core/_cards.css` seems like a good idea here. Be sure to create the consummate `@import` statement in `src/skeleton.css` as well.

I see in your commit that you have added a bottom margin to the `row` class. Please remove that.

**Comment by ajbraus** [comment]
Can do. Thx for the feedback.

**Comment by ajbraus** [comment]
Ok I think I followed your directions. I had one problem which was `npm run build` didn't update `dist/index.html`.

**Comment by gld1982ltd** [comment]
Go ahead and copy the src index.html to the dist folder. Working on the build system in a different commit. Thanks

**Comment by enlore** [comment]
Got it. Gonna bumped this to 1.1.0 as well, since we have new features.

Thanks @ajbraus!

**Pull request merged**
